version: '2'

services:
    selenoid:
        image: aerokube/selenoid:latest-release
        network_mode: bridge
        volumes:
          - "$PWD/browsers.json:/etc/selenoid/browsers.json"
          - "/var/run/docker.sock:/var/run/docker.sock"
        command: ["-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs"]
        ports:
          - "4444:4444"

    selenoid-ui:
        image: aerokube/selenoid-ui
        network_mode: bridge
        links:
          - selenoid
        ports:
            - 8080:8080
        command: --selenoid-uri http://selenoid:4444